### ISSUE TITLE
[custom-buildpack] Documentation suggestion: how to currently use the custom buildpack

### ISSUE THREAD

**Issue by holtkamp** [cloudControl/buildpack-php#31]
Ok, I think I just found a nice approach to currently use the custom-php-buildpack approach without having to change to much to a CloudControl deployment:

- The Buildpack parses the ```composer.json``` file to determine which PHP version / extensions need to be installed after the ```cctrlapp application/deployment push``` is received
- Composer itself prefers the ```composer.lock``` file (if available) to install the application dependencies. 

Conclusion, when deploying an application to CloudControl, do NOT use the same ```composer.json``` file that was used for the application, only commit the generated ```composer.lock``` file. This is something that can be done during an automated build process. 

Note that this approach *will* generate a warning message like:

```Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.```

But this is expected and can therefore be ignored.

**Comment by havvg** [comment]
What's the use of this?

For an deployed application, you should commit the `composer.json` as well as the `composer.lock`. Any deployment will use the `composer.lock` file and therefore use the locked versions of the dependencies.

Installing dependencies with a missing `composer.lock` will not ensure specific versions of the dependencies, but most recent version that match the version constraint defined in the `composer.json`.

**Comment by holtkamp** [comment]
@havvg , you are right. Combined with support for https://github.com/cloudControl/buildpack-php/issues/35 your answer makes perfect sense.

However, for the time being, the suggested approach forms a work-around to be able to experiment with the use of the custom-buildpack which supports PHP 5.5.23 and PHP 5.6.10.
