### ISSUE TITLE
[custom-buildpack] PHP-CLI not configured correctly

### ISSUE THREAD

**Issue by holtkamp** [cloudControl/buildpack-php#32]
During startup of the container, we run some PHP scripts using PHP-CLI which require the cURL extension. When checking why these scripts fail when using the custom-buildpack with the PHP 5.5.23 image, two problems were identified:

- wrong php executable is used? This is stil on PHP 5.4..
- incorrect path used for the main and additional parsed .ini files

```
cctrlapp application/deployment run bash

~$ php -v
PHP 5.4.41-1+deb.sury.org~precise+2 (cli) (built: May 24 2015 15:41:28) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

~$ php --ini
Configuration File (php.ini) Path: /etc/php5/cli
Loaded Configuration File:         /etc/php5/cli/php.ini
Scan for additional .ini files in: /app/php/conf
Additional .ini files parsed:      (none)

~$ /srv/www/php-5.5.23/bin/php -v 
PHP 5.5.23 (cli) (built: Apr 22 2015 16:53:10) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

~$ /srv/www/php-5.5.23/bin/php --ini
Configuration File (php.ini) Path: /srv/www/php-5.5.23/etc
Loaded Configuration File:         (none)
Scan for additional .ini files in: /app/php/conf
Additional .ini files parsed:      (none)
```

Note that for the latter one, NO ini files are parsed at all...

The path to the additional .ini files is ```/srv/www/php-5.5.23/etc/conf.d/extensions.ini```

With this command I managed to get the extensions loading, but it is not the ideal solution:
```/srv/www/php-5.5.23/bin/php -c /srv/www/php-5.5.23/etc/conf.d/extensions.ini```

**Comment by TooAngel** [comment]
Yes, thx, for the information, I will have a look.

**Comment by TooAngel** [comment]
I could fix already the ini files. (https://github.com/cloudControl/buildpack-php/commit/09caa2f1047e9c8368ce6d97b7beb1e5c8d96cf6). After a new build the ini files should be parsed as expected.

To get directly the correct php version you can use 'bash -l' for a login shell, which sets the correct path automatically. (`cctrlapp APP_NAME/DEP_NAME run 'bash -l'`) We will work on having the `.profile.d` parsed directly.

**Comment by TooAngel** [comment]
`run bash` is fixed now, too. More a workaround but I think it should be fine for now, until we have a more global solution.

**Comment by holtkamp** [comment]
fix confirmed :+1:
