### ISSUE TITLE
[custom-buildpack] Missing APCu extension for PHP >= 5.5 

### ISSUE THREAD

**Issue by holtkamp** [cloudControl/buildpack-php#33]
PHP 5.5 comes bundled with [opcache](http://php.net/manual/en/book.opcache.php), which is a replacement for the OPCODE part of [APC](http://php.net/manual/en/book.apc.php)

Enabling ```opcache``` this can be done with an additional file: ```.buildpack/php/conf/opcache.ini```:

```
[OPcache]
zend_extension = opcache.so
```

Great! PHP files are now OPCODE cached.

However, APC *also* offered a User Cache => a place to quickly store application information in memory. This is great when using a two-level cache, for example:

- APC User Cache as a fast cache, not persisted, every redeploy of the container the cache is cleared
- database as a slow cache, persistent, acts a fall back mechanism. 

For PHP 5.5, [it is advised](http://jessesnet.com/development-notes/2014/php-55-opcache-apcu/) to use [APCu](https://pecl.php.net/package/APCu), the user part of APC. 

Trying to install it with ```composer.json```: 

    "require": {
        "php-64bit": "5.5.23",
        "ext-apcu": "*"
	}
	
Results in a warning:

```
-----> Receiving push
-----> Using php version 5.5.23
-----> Installing composer dependencies...
PHP Warning:  PHP Startup: Unable to load dynamic library '/srv/www/php-5.5.23/lib/php/extensions/apcu.so' - /srv/www/php-5.5.23/lib/php/extensions/apcu.so: cannot open shared object file: No such file or directory in Unknown on line 0
```

Can this extension be added to the list of allowed extensions? This way applications that used APC on PHP 5.4 will not break, since APCu is compatible.

**Comment by TooAngel** [comment]
I added the APCu extension to the php build (https://github.com/cloudControl/buildpack-php/commit/e70a279bcb24bdbe1a3fd5ad5321433b68cbe8ff). php-5.5.23 and php-5.6.10 are also build with added apcu, on your next build `ext-apcu` should be available.
It is also still possible to add the `.so` files to your repository and add the extension via the `php.ini.`. We are still discussing which extensions should be part of the php build.

**Comment by holtkamp** [comment]
Great, works as expected, closing issue
