### ISSUE TITLE
[custom-buildpack] allow wildcard PHP version constraints

### ISSUE THREAD

**Issue by havvg** [cloudControl/buildpack-php#35]
Currently you have to use the most specific version constraint, for example:

```
    "require": {
        "php-64bit": "5.5.23",
    }
```

It would be great to be able to use `~5.5.10`, so composer will run smoothly e.g. on local environments, that do not match the patch version.

**Comment by TooAngel** [comment]
Yes, this would be nice :-) We are working on providing the most recent php-versions, so that you can have the same php version on you local environment as well as on cloudControl. Which versions are you missing?

We also have a look how to handle 'wildcard' version string.

**Comment by havvg** [comment]
It's not a missing version, I got a workaround on this (modifying the composer.json to install locally). In this case it's `5.5.25` (and `5.6.9`) which I got locally installed. 

I would focus on the wildcard, instead of providing specific patch versions. Although those are sometimes introducing bugs, which causes you not to want to update to the new version.

**Comment by TooAngel** [comment]
Would it help in the first step to try to match the version, as if `~` where missing.
Resolving the ranges is a bit more complicated.

**Comment by holtkamp** [comment]
Would it not be possible to use the Composer functionality to determine the most appropriate version and install that one using the [Command Events](https://getcomposer.org/doc/articles/scripts.md#command-events) ?

The whole dependency resolution mechanism is something you don't want to re-invent yourselves ;)

**Comment by TooAngel** [comment]
The main issue here (not only here :-)) is, that composer is started already with the pre-configured php. So before composer is executed the php version needs to be set.

**Comment by holtkamp** [comment]
true, but for the current approach of the custom-buildpack, already two versions of PHP are used:
- a standard version (currently PHP 5.4), can be used to startup composer etc
- other version, as indicated in ```composer.json```

This might imply that as part of the composer installation (using the default PHP version), either:
 - a specific version of PHP is determined and installed and a new composer installation is started, like being a sub process
 - a specific version of PHP is determined and installed and composer exits with a (new?) specific [exit code](https://getcomposer.org/doc/03-cli.md#process-exit-codes) to inform the build process to 'restart' composer using the new php-cli? 

I think there is a way here, but maybe I am completely wrong. My point is that it seems viable to harness the strength of Composer for the complete build process.

**Comment by sgotre** [comment]
You can use composers ```--ignore-platform-reqs ```on your development machine if it does not match the exact requirements

**Comment by TooAngel** [comment]
Finally I was able to resolve wildcard (~) versions. For this we are using semver.io extended for php.
I added the commit to the customphp branch.
https://github.com/cloudControl/buildpack-php/commit/32dbd555c2446269920ab9848dc8bc758c5c3a55

**Comment by holtkamp** [comment]
```
"require": {
        "php-64bit": "~5.6"
}
```

Works nice, this issue can therefore be closed?

**Comment by havvg** [comment]
Thanks :-)
