### ISSUE TITLE
Using custom PHP is resulting in error

### ISSUE THREAD

**Issue by lbayerl** [cloudControl/buildpack-php#41]
I was trying to deploy with Custom PHP in composer  and it produced the following error:

-----> Receiving push
-----> Found php version definition ~5.5.28
-----> Using php version php-5.5.28
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
 !     cloudControl push rejected, failed to compile php app
 !

**Comment by TooAngel** [comment]
I guess you are using dotcloud. php-5.5.28 was not yet made available on dotcloud, while the available versions file was already updated. I released 5.5.28 for dotcloud, too. So you should be fine now. Sorry for the inconveniences.

**Comment by lbayerl** [comment]
Thanks - I am on Exoscale - should it work there now as well?

**Comment by TooAngel** [comment]
Yes, it should work there now, too.

**Comment by TooAngel** [comment]
Is this issue fixed?

**Comment by lbayerl** [comment]
as soon as I was able to test it I will confirm, relates to http://stackoverflow.com/questions/32410625/how-to-add-one-extension-to-standard-stack-after-pinky
