### ISSUE TITLE
LIBXML2_2.9.0 not found when depending on php-5.6.12

### ISSUE THREAD

**Issue by holtkamp** [cloudControl/buildpack-php#42]
Pushing at 04-09-2015 around 12:00 GMT+0200 seems to fail because of a missing library: 

```
cctrlapp projectName/acceptation push

Counting objects: 244, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (210/210), done.
Writing objects: 100% (244/244), 47.18 KiB | 0 bytes/s, done.
Total 244 (delta 173), reused 0 (delta 0)
       
-----> Receiving push
-----> Found php version definition 5.6.12
-----> Using php version php-5.6.12
-----> Installing composer dependencies...
php: /usr/lib/x86_64-linux-gnu/libxml2.so.2: version `LIBXML2_2.9.0' not found (required by php)
 !     cloudControl push rejected, failed to compile custom app
 !     
-----> Custom buildpack provided
remote: error: hook declined to update refs/heads/acceptation
```

around 11:30 a push to our test environment still worked...

**Comment by TooAngel** [comment]
Thank you for the info, I'm currently fixing the issue.

**Comment by holtkamp** [comment]
Thanks for the swift response. 

Just being curious, are you guys informed of such errors as well? Big dashboard in the cantina, sirens that start whooping, that idea? :smile:

**Comment by TooAngel** [comment]
We have regular checks which pushes with each of the available php versions defined, which also informed me about the problem.

The issues should be fixed by now, sorry for any inconveniences.

**Comment by holtkamp** [comment]
Confirmed, working again, closing issue.
