### ISSUE TITLE
ext-pdo_mysql not working with php 5.6.12

### ISSUE THREAD

**Issue by ertogs** [cloudControl/buildpack-php#43]
having this composer.json

    [...]
    "require": {
        "php-64bit": "5.6.12",        
        "ext-curl": "*",
        "ext-mcrypt": "*",
        "ext-zip": "*",
        "ext-pdo": "*",
        "ext-pdo_mysql": "*"
    },
    [...]

results in this error: 

PHP Warning:  PHP Startup: Unable to load dynamic library '/srv/www/php-5.6.12/lib/php/extensions/pdo_mysql.so' - /srv/www/php-5.6.12/lib/php/extensions/pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0

This also did not work with php-64bit 5.6.13

**Comment by TooAngel** [comment]
For `pdo_mysql` php also requires the `mysqlnd` extension.

```
{
    "require": {
        "php-64bit": "~5.6",
        "ext-mysqlnd": "*",
        "ext-pdo_mysql": "*",
        "ext-pdo": "*"
    }
}
```

We didn't include any special php extension dependencies resolving yet.

**Comment by ertogs** [comment]
Great, that's it. Thank you! :+1:  :)
