### ISSUE TITLE
Using custom PHP resulting in error again

### ISSUE THREAD

**Issue by lbayerl** [cloudControl/buildpack-php#44]
This time by using "php-64bit": ">=5.5 <7.0" again I receive a 
"-----> Found php version definition >=5.5 <7.0
 !     cloudControl push rejected, failed to compile php app"

Locally I have a PHP 5.5 (>=5.5) but I want to try a remote 5.6 (< 7.0). Otherwise I have to use two different definitions for local and remote deployment which I want to avoid in any case.

**Comment by TooAngel** [comment]
The issue was resolving versions with a space. This is fixed now, can you please try again?

**Comment by lbayerl** [comment]
confirmed, thanks.
