### ISSUE TITLE
Deployment fails for "standard" extension

### ISSUE THREAD

**Issue by lbayerl** [cloudControl/buildpack-php#45]
While trying to deploy with custom-php (~5.5.28 resulting in a found 5.5.29 version) on Exoscale I receive an error:

PHP Warning:  PHP Startup: Unable to load dynamic library '/srv/www/php-5.5.29/lib/php/extensions/pdo_mysql.so' - /srv/www/php-5.5.29/lib/php/extensions/pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0
(...)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-pdo_mysql * is missing from your system.

But according to http://www.paasfinder.com/custom-php-version/ ext-pdo_mysql is one of the standard requirements which will be required even if I don't use the custom-php since 14.09.2015.

**Comment by pst** [comment]
This is not a bug in the buildpack. If you require `ext-pdo_mysql`, you have to require `ext-mysqlnd` as well. See #43 for more details.

**Comment by lbayerl** [comment]
Can you provide some documentation for these dependencies if they are more of them?

**Comment by pst** [comment]
I think this is out of scope since it's not specific to the buildpack.
